/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CaesarCipher;

import java.util.Scanner;

import static CaesarCipher.Encrypt.encryptClass;
import static CaesarCipher.Decrypt.dencryptClass;

public class App {


    public static void main(String[] args) {
        Scanner myScanner = new Scanner(System.in);

        System.out.println("╔═══╗░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░\n" +
                "║╔═╗║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░\n" +
                "║║░╚╝╔══╗╔══╗╔══╗╔══╗╔═╗░░░░░░░░░░░░░░░░\n" +
                "║║░╔╗║╔╗║║║═╣║══╣║╔╗║║╔╝░░░░░░░░░░░░░░░░\n" +
                "║╚═╝║║╔╗║║║═╣╠══║║╔╗║║║░░░░░░░░░░░░░░░░░\n" +
                "╚═══╝╚╝╚╝╚══╝╚══╝╚╝╚╝╚╝░░░░░░░░░░░░░░░░░\n" +
                "╔═══╗░░░░░░╔╗░░░░░░░░░░░░░░░░░░░░░░░░░░░\n" +
                "║╔═╗║░░░░░░║║░░░░░░░░░░░░░░░░░░░░░░░░░░░\n" +
                "║║░╚╝╔╗╔══╗║╚═╗╔══╦═╗░░░░░░░░░░░░░░░░░░░\n" +
                "║║░╔╗╠╣║╔╗║║╔╗║║║═╣╔╝░░░░░░░░░░░░░░░░░░░\n" +
                "║╚═╝║║║║╚╝║║║║║║║═╣║░░░░░░░░░░░░░░░░░░░░\n" +
                "╚═══╝╚╝║╔═╝╚╝╚╝╚══╩╝░░░░░░░░░░░░░░░░░░░░\n" +
                "░░░░░░░║║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░\n" +
                "░░░░░░░╚╝░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░\n");

        System.out.println("============================");
        System.out.println("Enter Message");
        String message = myScanner.nextLine();

        System.out.println("Enter Key");
        int shift = myScanner.nextInt();
        myScanner.nextLine();

        System.out.println(encryptClass(message, shift));

        System.out.println("============================");

        System.out.println("Enter encrypted message");
        String decMessage = myScanner.nextLine();

        System.out.println("Enter key used to decrypt");
        int decShift = myScanner.nextInt();
        myScanner.nextLine();


        System.out.println(dencryptClass(decMessage, decShift));
    }

}
