/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CaesarCipher;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        Scanner myScanner = new Scanner(System.in);
        System.out.println("Enter Message");
        String message = myScanner.nextLine();

        System.out.println(message);

        System.out.println(new App().getGreeting());
    }
    public String getGreeting() {

        return "Hello world.";
    }
}
